// <auto-generated />
using System;
using KpopCardTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KpopCardTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("KpopCardTracker.Models.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficialCardNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("KpopCardTracker.Models.CardTag", b =>
                {
                    b.Property<Guid>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CardId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CardTags");
                });

            modelBuilder.Entity("KpopCardTracker.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TagTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagTypeId");

                    b.HasIndex("Name", "TagTypeId")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("KpopCardTracker.Models.TagType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TagTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBuiltIn = true,
                            Name = "Group"
                        },
                        new
                        {
                            Id = 2,
                            IsBuiltIn = true,
                            Name = "Member"
                        },
                        new
                        {
                            Id = 3,
                            IsBuiltIn = true,
                            Name = "Album"
                        },
                        new
                        {
                            Id = 4,
                            IsBuiltIn = true,
                            Name = "Album Version"
                        },
                        new
                        {
                            Id = 5,
                            IsBuiltIn = true,
                            Name = "Year"
                        },
                        new
                        {
                            Id = 6,
                            IsBuiltIn = true,
                            Name = "Card Number"
                        });
                });

            modelBuilder.Entity("KpopCardTracker.Models.CardTag", b =>
                {
                    b.HasOne("KpopCardTracker.Models.Card", "Card")
                        .WithMany("CardTags")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KpopCardTracker.Models.Tag", "Tag")
                        .WithMany("CardTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("KpopCardTracker.Models.Tag", b =>
                {
                    b.HasOne("KpopCardTracker.Models.TagType", "TagType")
                        .WithMany("Tags")
                        .HasForeignKey("TagTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagType");
                });

            modelBuilder.Entity("KpopCardTracker.Models.Card", b =>
                {
                    b.Navigation("CardTags");
                });

            modelBuilder.Entity("KpopCardTracker.Models.Tag", b =>
                {
                    b.Navigation("CardTags");
                });

            modelBuilder.Entity("KpopCardTracker.Models.TagType", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
